services:
  backend:
    build:
      context: ../..
      dockerfile: backend/docker/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
      - bot_logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/restaurant
      - INITIALIZE_DB=true
      # Bot conversation logging settings
      - BOT_LOG_LEVEL=INFO
      - BOT_LOG_FORMAT=json
      - BOT_FILE_LOGGING=true
      - BOT_LOG_DIR=/app/logs
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=restaurant
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  bot_logs: